server:
  port: 9990

spring:
  application:
    name: ribbon-a

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8990/eureka
    healthcheck:
      enabled: true
    instance:
      prefer-ip-address: true


eureka-client-a:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    listOfServers: localhost:11100,localhost:11101
ribbon:
  eureka:
    enabled: false