spring:
  profiles:
    active: dev, updlo
  application:
    name: eureka-client-a
server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8990/eureka
    instance:
      prefer-ip-address: true

pays:
  zf: jksdfs.dfe