server:
  port: 8990
spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8990/eureka
    register-with-eureka: false
    fetch-registry: false
